
{% set data = load_setup_py_data() %}

package:
  name: layer_viewer
  
  version: {{ data['version'] }}
  
source:
  path: ../


build:
  noarch: python
  number: 0
  
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  
requirements:
  host:
    - python
  run:
    - python >=3.6
    # dependencies are defined in setup.py
    
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    
test:
  imports:
    - layer_viewer

about:
  home: https://github.com/DerThorsten/layer_viewer
  license: MIT
  license_family: MIT
  
  license_file: ../LICENSE.txt
  summary: 'layer-viewer is a pyqt / pyqtgraph based layer viewer for 2d images'
  description: 'layer-viewer is a pyqt / pyqtgraph based layer viewer for 2d images'
  documentation_url: https://readthedocs.org/projects/layer_viewer/
  dev_url: https://github.com/DerThorsten/layer_viewer

extra:
  recipe-maintainers:
    - Thorsten Beier


